// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARAUIi7i8ighO2lJqZ33kw1KjB2ExZS8g',
    appId: '1:584918705504:web:aebd6cc197d232dd8dea05',
    messagingSenderId: '584918705504',
    projectId: 'to-do-7f395',
    authDomain: 'to-do-7f395.firebaseapp.com',
    storageBucket: 'to-do-7f395.firebasestorage.app',
    measurementId: 'G-PXMD4HS1DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0JB8IXLwWbowU9UgWVJefVD-6xcmcEhA',
    appId: '1:584918705504:android:a746c0497fa71fe68dea05',
    messagingSenderId: '584918705504',
    projectId: 'to-do-7f395',
    storageBucket: 'to-do-7f395.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5nh_8q10BhmXMy_yxidFbBakYLR12tAo',
    appId: '1:584918705504:ios:186955258df692e38dea05',
    messagingSenderId: '584918705504',
    projectId: 'to-do-7f395',
    storageBucket: 'to-do-7f395.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5nh_8q10BhmXMy_yxidFbBakYLR12tAo',
    appId: '1:584918705504:ios:186955258df692e38dea05',
    messagingSenderId: '584918705504',
    projectId: 'to-do-7f395',
    storageBucket: 'to-do-7f395.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARAUIi7i8ighO2lJqZ33kw1KjB2ExZS8g',
    appId: '1:584918705504:web:ef6394761cfefc088dea05',
    messagingSenderId: '584918705504',
    projectId: 'to-do-7f395',
    authDomain: 'to-do-7f395.firebaseapp.com',
    storageBucket: 'to-do-7f395.firebasestorage.app',
    measurementId: 'G-H1YBCST0WQ',
  );
}
